### PR TITLE
Remove logback as a main dependency

### PR DESCRIPTION
**Pull request by MariusVolkhart**
Popular Java logging technologies like SLF4J/Logback, and Log4J2, split the process of logging into 2 components: a logging frontend, and a logging backend. The logging frontend is the API that libraries and applications use to notify the logging system that they have something to report. The logging backend is used only by applications, not libraries, to determine how and where to log the stream of events that are coming from application code, as well as various libraries.

SLF4J is a logging frontend. Logback is a logging backend.

The popular logging technologies have adapters to work with one another. For example, Log4J2 can be used as a backend for SLF4J, and Logback can be used as a backend for JUL.

This library has chosen to code against the SLF4J API to report events that should be logged. However, this library should not dictate to consuming applications the logging backend they should use to process the log events, which it does by declaring a dependency on Logback. Accordingly, this commit removes the main dependency on Logback.

### CODE REVIEW

**Comment by nguyenq** [comment]
@grahams Can you help review the PR?

**Review by grahams — APPROVED** [review]
This looks good!

We actually ended up encountering a problem with the logback dependency in our product, solved it in a similar manner, but I hadn't gotten around to making the PR for it yet.

**Comment by nguyenq** [comment]
Thank you all.

**Comment by nguyenq** [comment]
@MariusVolkhart @grahams  I encountered some warning messages at the beginning of the unit tests, but the tests completed successfully anyway.

> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> Running net.sourceforge.tess4j.TessAPI1Test
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by nguyenq** [comment]
Adding this seems to have resolved it. 

>         <dependency>
>             <groupId>org.slf4j</groupId>
>             <artifactId>slf4j-simple</artifactId>
>             <version>1.7.30</version>
>         </dependency>

**Comment by grahams** [comment]
@nguyenq I think that the intent of @MariusVolkhart's inclusion of logback just in the `test` scope was to fullfill the need for a logging binding during testing.  If it is still not finding a binding during test there must be something else wrong, but I leave that to @MariusVolkhart because I'm not as familar with the unit testing on this package.

**Comment by MariusVolkhart** [comment]
@nguyenq Sorry about that! @grahams That was indeed the intention, however, I change the dependency from `logback-classic` to `logback-core`, which looks to be the source of the issue.

Using `slf4j-simple` is an option, but reports all messages to `std.err` instead of logging them as configured in `logback-test.xml`

I made #202 to track the issue.

**Pull request merged**
